# Generated by Django 4.2.4 on 2023-08-16 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='make_date',
            field=models.PositiveIntegerField(),
        ),
    ]
