# Generated by Django 4.2.4 on 2023-08-14 02:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='list_date',
            field=models.DateField(blank=True, default=datetime.date(2023, 8, 14)),
        ),
        migrations.AlterField(
            model_name='listing',
            name='make_date',
            field=models.DateField(blank=True, default=datetime.date(2023, 8, 14)),
        ),
    ]
