# Generated by Django 4.2.4 on 2023-08-14 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_alter_listing_list_date_alter_listing_make_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='photo_5',
        ),
    ]
