# Generated by Django 4.2.4 on 2023-08-14 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_remove_listing_photo_5'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='engine_size',
            field=models.FloatField(),
        ),
    ]
