# Generated by Django 4.2.4 on 2023-08-15 22:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_alter_listing_list_date_alter_listing_make_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='list_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='listing',
            name='make_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
